Repository cbnu-sequence/sequence-web-front, pull requests merged in 2022-06, with the labels that each got.

#98 response status처리 및 반응형 디자인 수정
  components/ProjectWrite/index.tsx
  components/ProjectWrite/styles.tsx
  components/WriteBoard/index.tsx
  components/WriteBoard/styles.tsx
  components/WriteBoard/texteditor.tsx
  pages/introduce/index.tsx
  styles/introduce.ts
Labels: 초강력 코드리뷰😎

#105 Add: 부원 소개 페이지 추가
  apis/user.ts
  components/Header/index.tsx
  components/Header/styles.tsx
  hooks/useProjectMembers.ts
  pages/members/manager/index.tsx
  pages/members/projectteam/index.tsx
  pages/members/techcourseteam/index.tsx
  styles/projectTeam.ts
  styles/techcourseTeam.ts
  yarn.lock
Labels: 초강력 코드리뷰😎

#106 Add: 나의 뽀모도로 리스트
  apis/pomodoro.ts
  components/MyPomo/index.tsx
  components/MyPomo/styles.ts
  components/PomoProgress/index.tsx
  components/PomoProgress/styles.ts
  components/Ranking/index.tsx
  components/Timer/index.tsx
  components/TimerForm/index.tsx
  pages/pomodoro/index.tsx
  react-query/constants.ts
  styles/pomodoro.ts
Labels: 초강력 코드리뷰😎, 디자인 수정🪄

#109 Add: 프로필 수정 추가
  apis/user.ts
  components/Header/styles.tsx
  interfaces/user.ts
  pages/emailcheckprofile/index.tsx
  pages/members/manager/index.tsx
  pages/profile/index.tsx
  react-query/constants.ts
  styles/profile.ts
Labels: 초강력 코드리뷰😎

#111 Add: 프로필 수정하기 기능 수정
  pages/emailcheckprofile/index.tsx
  pages/profile/index.tsx
Labels: 초강력 코드리뷰😎

#115 Add:운영진 페이지 추가
  pages/members/manager/index.tsx
  styles/manager.ts
Labels: 초강력 코드리뷰😎

#116 Add: 이메일 인증 컴포넌트화
  components/EmailCheckProfile/index.tsx
  components/EmailCheckProfile/styles.tsx
  pages/emailcheckprofile/index.tsx
  pages/profile/index.tsx
Labels: 초강력 코드리뷰😎

#125 Fix compile Error & SSR
  Dockerfile.prod
  pages/members/projectteam/index.tsx
  pages/members/techcourseteam/index.tsx
Labels: 버그가 있어요🐞

#132 Add: 회원가입 버튼 수정
  hooks/useAuth.ts
  pages/login/index.tsx
  pages/signup/index.tsx
  styles/signup.ts
Labels: 초강력 코드리뷰😎
