Repository cbnu-sequence/sequence-web-front, pull requests merged in 2022-07, with the labels that each got.

#137 Add: 프로젝트 디테일 페이지 추가
  apis/post.ts
  components/ImageSlider/index.tsx
  components/ImageSlider/styles.tsx
  components/ProjectCard/index.tsx
  components/ProjectCard/styles.tsx
  components/ProjectDetail/index.tsx
  components/ProjectDetail/styles.tsx
  components/ZoomImage/index.tsx
  components/ZoomImage/styles.tsx
  package-lock.json
  pages/project/[id].tsx
  yarn.lock
Labels: 초강력 코드리뷰😎

#139 Add: 프로필 페이지 디자인 수정
  components/ImageSlider/index.tsx
  components/ImageSlider/styles.tsx
  components/ProjectDetail/index.tsx
  components/ProjectDetail/styles.tsx
  components/ZoomImage/index.tsx
  components/ZoomImage/styles.tsx
Labels: 디자인 수정🪄

#141 Add: Readme수정
  README.md
Labels: 디자인 수정🪄

#146 Add: 게시판 수정 기능 추가
  apis/post.ts
  components/EditBoard/index.tsx
  components/PostDetail/index.tsx
  components/PostDetail/styles.tsx
  pages/posts/[id].tsx
  pages/posts/edit/[id].tsx
  user-storage/user-storage.ts
Labels: 초강력 코드리뷰😎

#149 Add: 프로젝트 디테일 페이지 디자인 수정
  components/ProjectDetail/styles.tsx
  components/ZoomImage/styles.tsx
Labels: 디자인 수정🪄

#152 부원소개 - 프로젝트팀, 테크코스팀 디자인 수정하였습니다.
  styles/projectTeam.ts
  styles/techcourseTeam.ts
Labels: 디자인 수정🪄

#150 Add: ssr작업 추가
  components/EditBoard/index.tsx
  pages/posts/edit/[id].tsx
Labels: 초강력 코드리뷰😎

#156 Add: 프로필 페이지 멤버 정보 변경 기능 추가
  apis/user.ts
  pages/profile/index.tsx
  styles/profile.ts
Labels: 초강력 코드리뷰😎

#154 부원 소개 - 운영진 소개 및 모바일 뷰 수정했습니다.
  components/ManagerCard/styles.tsx
  components/ProfileModal/styles.tsx
  pages/members/manager/index.tsx
  styles/manager.ts
  styles/techcourseTeam.ts
Labels: 디자인 수정🪄

#162 Add: 헤더 리팩토링
  components/Header/index.tsx
  components/Header/styles.tsx
Labels: 코드 개선😎

#164 프로필 디자인 수정
  components/EmailCheckProfile/index.tsx
  components/EmailCheckProfile/styles.tsx
  pages/profile/index.tsx
  styles/profile.ts
Labels: 디자인 수정🪄

#161 Add: 프로젝트 디테일 페이지 수정
  components/ImageSlider/index.tsx
  components/ImageSlider/styles.tsx
  components/ProjectDetail/index.tsx
  components/ProjectDetail/styles.tsx
  components/ZoomImage/index.tsx
  components/ZoomImage/styles.tsx
Labels: 디자인 수정🪄

#166 Support: 부원소개 모바일뷰 수정
  components/ProfileModal/styles.tsx
  pages/members/manager/index.tsx
  pages/members/techcourseteam/index.tsx
  styles/techcourseTeam.ts
Labels: 디자인 수정🪄

#170 디자인 수정
  components/Buttons/styles.tsx
  components/NoList/styles.tsx
  components/PostDetail/index.tsx
  components/PostDetail/styles.tsx
  components/PostHeader/styles.tsx
  components/ProjectDetail/styles.tsx
  components/ProjectImage/index.tsx
  components/ProjectWrite/index.tsx
  components/ProjectWrite/styles.tsx
  components/Table/styles.tsx
  pages/board/notice/index.tsx
  pages/board/sharinginfo/index.tsx
  pages/profile/index.tsx
  styles/profile.ts
Labels: 디자인 수정🪄

#178 Improvement: 컴포넌트화
  components/EmailCheckProfile/styles.tsx
  components/Manager/index.tsx
  components/Manager/styles.tsx
  components/ProfileMain/ProfileMainButton/index.tsx
  components/ProfileMain/ProfileMainButton/styles.tsx
  components/ProfileMain/ProfileMainScreen/index.tsx
  components/ProfileMain/ProfileMainScreen/styles.tsx
  components/ProfileMain/index.tsx
  components/ProfileMain/styles.tsx
  components/ProjectTeam/index.tsx
  components/ProjectTeam/styles.tsx
  components/TechCourseTeam/index.tsx
  components/TechCourseTeam/styles.tsx
  pages/members/manager/index.tsx
  pages/members/projectteam/index.tsx
  pages/members/techcourseteam/index.tsx
  pages/profile/index.tsx
  styles/profile.ts
Labels: 코드 개선😎
