Repository cbnu-sequence/sequence-web-front, pull requests merged in 2022-05, with the labels that each got.

#24 게시글쓰기 페이지 디자인 통일화
  apis/post.ts
  components/writeboard/index.tsx
  components/writeboard/styles.tsx
  components/writeboard/test/writeboard.test.tsx
  components/writeboard/texteditor.tsx
  jest.config.js
  jest.setup.js
  mocks/handler.js
  mocks/handlers.js
  package-lock.json
  package.json
  styles/constants.js
  yarn.lock
Labels: 초강력 코드리뷰😎, 디자인 수정🪄

#29 Add: 모바일뷰 헤더 서브메뉴 겹침 수정
  components/Header/styles.tsx
Labels: 디자인 수정🪄

#31 #30 헤더 로고 움직임
  components/Header/index.tsx
  components/Header/styles.tsx
  public/sequence_bf.png
  public/sequence_wf.png
Labels: 도움이 필요해요🙋‍♂️

#42 [SSR] 홈화면 getServerSideProps를 이용하여 내 정보 불러오기
  apis/post.ts
  components/Header/index.tsx
  components/Main/index.tsx
  components/PostDetail/index.tsx
  components/PostDetail/styles.tsx
  components/PostHeader/index.tsx
  components/PostHeader/styles.tsx
  hooks/roleToKr.ts
  pages/index.tsx
  pages/posts/[id].tsx
Labels: 성능 향상💪, 초강력 코드리뷰😎

#50 게시글 디테일 페이지 디자인 추가
  components/PostDetail/index.tsx
  components/PostDetail/styles.tsx
  components/PostFiles/index.tsx
  components/PostHeader/index.tsx
  components/PostHeader/styles.tsx
  components/PostImages/index.tsx
  pages/posts/[id].tsx
  pages/profile/index.tsx
Labels: 초강력 코드리뷰😎, 디자인 수정🪄

#51 Geunwoo2
  apis/post.ts
  components/Map/map.tsx
  components/writeboard/index.tsx
  components/writeboard/styles.tsx
  package-lock.json
  package.json
  pages/introduce/index.tsx
  pages/introduce/styles.tsx
  public/culture.png
  styles/constants.js
  yarn.lock
Labels: 초강력 코드리뷰😎

#57 Add: 파일 삭제 버튼 추가
  components/writeboard/index.tsx
  components/writeboard/styles.tsx
Labels: 초강력 코드리뷰😎

#59 Geunwoo2
  apis/post.ts
  components/Buttons/styles.tsx
  components/Header/index.tsx
  components/ProjectWrite/index.tsx
  components/ProjectWrite/styles.tsx
  components/writeboard/index.tsx
  components/writeboard/styles.tsx
  interfaces/user.ts
  pages/members/index.tsx
  pages/members/profilemodal.tsx
  pages/members/profilemodalstyles.tsx
  pages/members/styles.tsx
  pages/profile/index.tsx
Labels: 초강력 코드리뷰😎

#64 #63
  components/Buttons/styles.tsx
  components/Header/styles.tsx
  pages/board/notice/write/index.tsx
  pages/board/projects/write/index.tsx
  pages/introduce/index.tsx
  pages/members/index.tsx
  pages/profile/index.tsx
  pages/profile/styles.tsx
Labels: 버그가 있어요🐞, 초강력 코드리뷰😎, 디자인 수정🪄

#71 Add: 헤더 useEffect 오류 수정
  components/Header/index.tsx
Labels: 버그가 있어요🐞, 성능 향상💪, 초강력 코드리뷰😎

#73 리스트 없을 시 보여주는 컴포넌트 만들었습니다.
  components/NoList/index.tsx
  components/NoList/styles.tsx
  pages/board/notice/index.tsx
  public/flowerLogo_dg.png
Labels: 도움이 필요해요🙋‍♂️

#87 Add production [build & deploy] Setting
  Dockerfile.dev
  Dockerfile.prod
  components/404/styles.tsx
  next.config.js
  package-lock.json
  package.json
  pages/404/index.tsx
  yarn.lock
Labels: 성능 향상💪
